<a href="https://colab.research.google.com/github/Jayz87/pythonCrashCourse3rd/blob/main/PYtorchintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.1+cu121


Creating Tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.item()

7

In [4]:
#vector
vector = torch.tensor([7,17])
vector, scalar

(tensor([ 7, 17]), tensor(7))

In [6]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
#matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix,matrix.ndim,matrix[1],matrix.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 tensor([ 9, 10]),
 torch.Size([2, 2]))

In [14]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR,TENSOR.ndim,TENSOR.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 3,
 torch.Size([1, 3, 3]))

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [26]:
TENSOR2 = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]],[ [4,7,8],[5,6,9],[8,9,6]]])
TENSOR2,TENSOR2.ndim,TENSOR2.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],
 
         [[4, 7, 8],
          [5, 6, 9],
          [8, 9, 6]]]),
 3,
 torch.Size([2, 3, 3]))

In [27]:
TENSOR2[1]

tensor([[4, 7, 8],
        [5, 6, 9],
        [8, 9, 6]])